// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace FirstRecordAndPlayback
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// This Method Test the paint fonctions
        /// </summary>
        public void PaintWrite()
        {
            #region Variable Declarations
            WinClient uIAdsızPaintClient = this.UIAdsızPaintWindow.UIItemWindow.UIAdsızPaintClient;
            WinGroup uIItemGroup = this.UIAdsızPaintWindow.UIItemWindow1.UIRenklerToolBar.UIItemGroup;
            WinListItem uIAltıgenListItem = this.UIAdsızPaintWindow.UIItemWindow1.UIŞekillerClient.UIAltıgenListItem;
            WinControl uIDoldurDropDownButton = this.UIAdsızPaintWindow.UIItemWindow1.UIŞekillerToolBar.UIDoldurDropDownButton;
            WinMenuItem uIDüzrenkMenuItem = this.UIAdsızPaintWindow.UIItemWindow1.UIDoldurClient.UIItemGroup.UIDüzrenkMenuItem;
            WinButton uISilgiButton = this.UIAdsızPaintWindow.UIItemWindow1.UIAraçlarToolBar.UISilgiButton;
            WinButton uISimgeDurumunaKüçültButton = this.UIAdsızPaintWindow.UIAdsızPaintTitleBar.UISimgeDurumunaKüçültButton;
            #endregion

            // Click 'Adsız - Paint' client
            Mouse.Click(uIAdsızPaintClient, new Point(24, 28));

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(24, 28));
            Mouse.StopDragging(uIAdsızPaintClient, -10, 50);

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(19, 31));
            Mouse.StopDragging(uIAdsızPaintClient, -2, 44);

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(69, 66));
            Mouse.StopDragging(uIAdsızPaintClient, 15, 25);

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(65, 82));
            Mouse.StopDragging(uIAdsızPaintClient, 18, 0);

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(62, 73));
            Mouse.StopDragging(uIAdsızPaintClient, 25, -5);

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(113, 76));
            Mouse.StopDragging(uIAdsızPaintClient, 10, 23);

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(113, 88));
            Mouse.StopDragging(uIAdsızPaintClient, 6, 20);

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(157, 63));
            Mouse.StopDragging(uIAdsızPaintClient, 21, -3);

            // Click 'Adsız - Paint' client
            Mouse.Click(uIAdsızPaintClient, new Point(168, 41));

            // Click 'Adsız - Paint' client
            Mouse.Click(uIAdsızPaintClient, new Point(158, 46));

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(207, 62));
            Mouse.StopDragging(uIAdsızPaintClient, 59, 31);

            // Click group
            Mouse.Click(uIItemGroup, new Point(180, 17));

            // Click 'Altıgen' list item
            Mouse.Click(uIAltıgenListItem, new Point(14, 6));

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(311, 50));
            Mouse.StopDragging(uIAdsızPaintClient, 37, 51);

            // Click 'Doldur' DropDownButton
            Mouse.Click(uIDoldurDropDownButton, new Point(30, 16));

            // Click 'Düz renk' menu item
            Mouse.Click(uIDüzrenkMenuItem, new Point(49, 6));

            // Click group
            Mouse.Click(uIItemGroup, new Point(152, 46));

            // Click group
            Mouse.Click(uIItemGroup, new Point(152, 45));

            // Click 'Adsız - Paint' client
            Mouse.Click(uIAdsızPaintClient, new Point(325, 82));

            // Click 'Silgi' button
            Mouse.Click(uISilgiButton, new Point(25, 7));

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(218, 107));
            Mouse.StopDragging(uIAdsızPaintClient, -30, -20);

            // Move 'Adsız - Paint' client
            Mouse.StartDragging(uIAdsızPaintClient, new Point(217, 48));
            Mouse.StopDragging(uIAdsızPaintClient, 31, 21);

            // Click 'Simge Durumuna Küçült' button
            Mouse.Click(uISimgeDurumunaKüçültButton, new Point(41, 9));
        }
        
        #region Properties
        public UIAdsızPaintWindow UIAdsızPaintWindow
        {
            get
            {
                if ((this.mUIAdsızPaintWindow == null))
                {
                    this.mUIAdsızPaintWindow = new UIAdsızPaintWindow();
                }
                return this.mUIAdsızPaintWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAdsızPaintWindow mUIAdsızPaintWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAdsızPaintWindow : WinWindow
    {
        
        public UIAdsızPaintWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Adsız - Paint";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSPaintApp";
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIAdsızPaintTitleBar UIAdsızPaintTitleBar
        {
            get
            {
                if ((this.mUIAdsızPaintTitleBar == null))
                {
                    this.mUIAdsızPaintTitleBar = new UIAdsızPaintTitleBar(this);
                }
                return this.mUIAdsızPaintTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIAdsızPaintTitleBar mUIAdsızPaintTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "Afx:", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public WinClient UIAdsızPaintClient
        {
            get
            {
                if ((this.mUIAdsızPaintClient == null))
                {
                    this.mUIAdsızPaintClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIAdsızPaintClient.WindowTitles.Add("Adsız - Paint");
                    #endregion
                }
                return this.mUIAdsızPaintClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIAdsızPaintClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Ribbon";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "NetUIHWND";
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public UIRenklerToolBar UIRenklerToolBar
        {
            get
            {
                if ((this.mUIRenklerToolBar == null))
                {
                    this.mUIRenklerToolBar = new UIRenklerToolBar(this);
                }
                return this.mUIRenklerToolBar;
            }
        }
        
        public UIŞekillerClient UIŞekillerClient
        {
            get
            {
                if ((this.mUIŞekillerClient == null))
                {
                    this.mUIŞekillerClient = new UIŞekillerClient(this);
                }
                return this.mUIŞekillerClient;
            }
        }
        
        public UIŞekillerToolBar UIŞekillerToolBar
        {
            get
            {
                if ((this.mUIŞekillerToolBar == null))
                {
                    this.mUIŞekillerToolBar = new UIŞekillerToolBar(this);
                }
                return this.mUIŞekillerToolBar;
            }
        }
        
        public UIDoldurClient UIDoldurClient
        {
            get
            {
                if ((this.mUIDoldurClient == null))
                {
                    this.mUIDoldurClient = new UIDoldurClient(this);
                }
                return this.mUIDoldurClient;
            }
        }
        
        public UIAraçlarToolBar UIAraçlarToolBar
        {
            get
            {
                if ((this.mUIAraçlarToolBar == null))
                {
                    this.mUIAraçlarToolBar = new UIAraçlarToolBar(this);
                }
                return this.mUIAraçlarToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIRenklerToolBar mUIRenklerToolBar;
        
        private UIŞekillerClient mUIŞekillerClient;
        
        private UIŞekillerToolBar mUIŞekillerToolBar;
        
        private UIDoldurClient mUIDoldurClient;
        
        private UIAraçlarToolBar mUIAraçlarToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRenklerToolBar : WinToolBar
    {
        
        public UIRenklerToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Renkler";
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public WinGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIItemGroup.WindowTitles.Add("Adsız - Paint");
                    #endregion
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIŞekillerClient : WinClient
    {
        
        public UIŞekillerClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public WinListItem UIAltıgenListItem
        {
            get
            {
                if ((this.mUIAltıgenListItem == null))
                {
                    this.mUIAltıgenListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIAltıgenListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Altıgen";
                    this.mUIAltıgenListItem.WindowTitles.Add("Adsız - Paint");
                    #endregion
                }
                return this.mUIAltıgenListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIAltıgenListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIŞekillerToolBar : WinToolBar
    {
        
        public UIŞekillerToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Şekiller";
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public WinControl UIDoldurDropDownButton
        {
            get
            {
                if ((this.mUIDoldurDropDownButton == null))
                {
                    this.mUIDoldurDropDownButton = new WinControl(this);
                    #region Search Criteria
                    this.mUIDoldurDropDownButton.SearchProperties[UITestControl.PropertyNames.Name] = "Doldur";
                    this.mUIDoldurDropDownButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "DropDownButton";
                    this.mUIDoldurDropDownButton.WindowTitles.Add("Adsız - Paint");
                    #endregion
                }
                return this.mUIDoldurDropDownButton;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIDoldurDropDownButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDoldurClient : WinClient
    {
        
        public UIDoldurClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIDüzrenkMenuItem
        {
            get
            {
                if ((this.mUIDüzrenkMenuItem == null))
                {
                    this.mUIDüzrenkMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIDüzrenkMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Düz renk";
                    this.mUIDüzrenkMenuItem.WindowTitles.Add("Adsız - Paint");
                    #endregion
                }
                return this.mUIDüzrenkMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIDüzrenkMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAraçlarToolBar : WinToolBar
    {
        
        public UIAraçlarToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Araçlar";
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public WinButton UISilgiButton
        {
            get
            {
                if ((this.mUISilgiButton == null))
                {
                    this.mUISilgiButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISilgiButton.SearchProperties[WinButton.PropertyNames.Name] = "Silgi";
                    this.mUISilgiButton.WindowTitles.Add("Adsız - Paint");
                    #endregion
                }
                return this.mUISilgiButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISilgiButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAdsızPaintTitleBar : WinTitleBar
    {
        
        public UIAdsızPaintTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Adsız - Paint");
            #endregion
        }
        
        #region Properties
        public WinButton UISimgeDurumunaKüçültButton
        {
            get
            {
                if ((this.mUISimgeDurumunaKüçültButton == null))
                {
                    this.mUISimgeDurumunaKüçültButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISimgeDurumunaKüçültButton.SearchProperties[WinButton.PropertyNames.Name] = "Simge Durumuna Küçült";
                    this.mUISimgeDurumunaKüçültButton.WindowTitles.Add("Adsız - Paint");
                    #endregion
                }
                return this.mUISimgeDurumunaKüçültButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISimgeDurumunaKüçültButton;
        #endregion
    }
}
